name: billbalancer
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pip=22.1.2
  - pyparsing=3.0.9
  - python=3.9.13
  - python-dateutil=2.8.2
  - pytz=2022.1
  - regex=2022.7.9
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tzdata=2022c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - autopep8==1.7.0
    - pycodestyle==2.9.1
    - toml==0.10.2
