name: billbalancer
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.9.13
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tzdata=2022c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
